config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="inner">
  <p class="app-footer"><%= copyright_generator %></p>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix masthead-cover">
  <div class="inner">
    <h3 class="masthead-brand"><%= link_to "Michael Harris", root_path, class: "nav-color" %></h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link', ' ' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Dev Thoughts</h1>
    <p class="lead blog-description">Musings from my software development journey</p>
    <% if logged_in?(:site_admin) %>
      <span>
        <%= link_to 'Write a New Blog', new_blog_path %>&nbsp;&nbsp;
      </span>
    <% end %>

    <span>
      <%= link_to 'Topics', topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="blog-masthead navbar navbar-expand-md navbar-dark blog-nav">
  <div class="container">
    <%= link_to "Michael Harris", root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav nav-pos">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper 'nav-link', ' ' %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-sm-3 ml-sm-auto blog-sidebar">
  <div class="sidebar-module sidebar-module-inset line-spacer">
    <h4>About Me</h4>
    <p>Software Development is my devotion. Creating new posibilities is my passion.</p>
  </div>

  <%= source_helper("alert alert-info line-spacer") %>

  <div class="sidebar-module pt-5">
    <h4>Topics:</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><%= link_to (fa_icon "github", class: "pr-2"), "https://github.com/michaelharris7", target: "_blank", alt: "My Github account" %></li>
      <li><%= link_to (fa_icon "linkedin-square", class: "pr-2"), "https://www.linkedin.com/in/michael-harris-58053a15a/", target: "_blank", alt: "My Linkedin account" %></li>
    </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <% unless request.original_fullpath == '/portfolios' %>
        <%= link_to "View All Portfolios", portfolios_path %> &nbsp;|&nbsp;
      <% end %>

      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<% if request.original_fullpath == '/portfolios' %>
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Portfolio</h1>
      <p class="lead text-muted">In this portfolio I've listed some of my favorite projects that I've built through the years. These applications capture a wide range of the applications that I love to develop.</p>
      <p>
        <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
        <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
      </p>
    </div>
  </section>
<% end %>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Check out my portfolio items below. These items are some of the projects I have developed over the years. Let me know what you think. I would love to hear from you.</p>
        </div>
        <div class="col-sm-4 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
            <li><%= login_helper 'text-white', '<br />' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="navbar navbar-dark bg-dark">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand">Michael Harris</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>